In [1]:
from win_prob import WinProb
import os
import csv
import pymysql as mc 
import time
import webbrowser
import sys
from sklearn.cluster import KMeans
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold, learning_curve
from sklearn.preprocessing import scale, PolynomialFeatures, LabelEncoder
from sklearn.neural_network import MLPClassifier
from pitcher_classification import Cluster_Data 
from importlib import reload

In [5]:
cnx = mc.connect(user='akashgoyal',password=os.environ['DB_PASSWORD'],
                 host='stromberg.cs.uchicago.edu',database='mlb_practicum')

In [6]:
a = WinProb(cnx,year=['2011','2012','2013','2014'])

done running query
done preparing new df for regression
done adding pythagorean wins
you can manually run the neural net now if you like by calling self.create_neural_net(number_nodes)


In [8]:
a.X.drop(columns=['balls','strikes'],inplace=True)

In [9]:
a.create_neural_net(15)

Your in sample Neural Network Score was 0.753435768784107


In [13]:
#now go out of sample and check this 
b = WinProb(cnx,year=['2015'])

done running query
done preparing new df for regression
done adding pythagorean wins
you can manually run the neural net now if you like by calling self.create_neural_net(number_nodes)


In [14]:
b.X.drop(columns=['balls','strikes'],inplace=True)

In [15]:
a.nn.score(b.X,b.Y)

0.75813510969063291

In [46]:
a.nn.predict_proba(b.X.iloc[100].reshape(1,-1))

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  """Entry point for launching an IPython kernel.


array([[ 0.56575886,  0.43424114]])

In [16]:
a.X.columns.values

array(['300_avg', '500_avg', '1000_avg', '2000_avg', 'timesFaced',
       'cumulativePitches', 'current_lead', (0, 0), (0, 1), (0, 2), (1, 0),
       (1, 1), (1, 2), (2, 0), (2, 1), (2, 2), (3, 0), (3, 1), (3, 2),
       '1b runner', '2b runner', '3b runner', 'mod inning', 'home_away',
       'p10', 'p30', 'p50', 'p100'], dtype=object)

In [17]:
a.nn.classes_

array([0, 1])

In [18]:
a.nn.loss_

0.47465424850177312

In [19]:
a.nn.n_iter_

201

In [20]:
a.nn.n_layers_

3

In [21]:
a.nn.intercepts_

[array([-0.26650394, -0.18005385, -0.360345  , -0.22450647, -0.20785674,
        -0.27092861, -0.49123157,  0.16577502, -0.36530038,  0.13041785,
         0.092918  , -0.0313311 ,  0.14366288, -0.18888618,  0.19808515]),
 array([-0.08254447])]

In [22]:
a.nn.coefs_

[array([[ -6.19933278e-02,   2.69882870e-01,  -3.73502751e-01,
          -1.39045777e-01,  -3.62758194e-01,  -2.75765106e-01,
          -3.24571848e-01,  -2.28814163e-02,  -2.16289389e-01,
           4.78525737e-02,   2.77542772e-02,   1.45446339e-01,
          -1.44738718e-01,   1.92369290e-01,  -4.46905509e-01],
        [  1.27352692e-01,   1.75107005e-02,   4.38080498e-02,
          -2.61655295e-01,  -3.00423631e-01,   2.45838415e-01,
           2.81765254e-01,  -7.01251876e-02,   3.85277450e-02,
           2.95496595e-01,   3.61377294e-01,  -3.04092573e-01,
          -2.86621940e-01,  -3.14878116e-01,   2.13653175e-01],
        [ -3.00070561e-01,   6.63740894e-04,   3.42049609e-01,
           3.04481490e-02,   8.67117643e-02,  -1.22853905e-01,
           8.83616423e-02,   3.01702034e-01,  -4.41006436e-01,
           1.98694420e-01,   4.15451437e-01,   1.90917249e-01,
          -1.20203413e-01,   1.64560184e-01,  -3.45057053e-01],
        [ -3.89276816e-02,   3.57748184e-01,  -1.542